# -*- coding: utf-8 -*-
"""Per-parameter explanations for the "?" help buttons (basic + advanced panels).

Content lives in HELP_TEXTS, keyed by the params_schema key. Rules:

* Every key must exist in core.params_schema.PARAMS_BY_KEY — pinned by
  tests/test_params_help.py.
* Values are Chinese-source literals; ui/param_help.py passes them through
  t(), so every CJK string also needs an _EN entry in core/i18n.py —
  pinned by tests/test_params_help.py.
* Text is based on llama.cpp: the --help strings in common/arg.cpp plus
  the source behaviour. Explanations are added tab by tab (model /
  context / sampling done first); the "?" button is only shown for keys
  present here, so coverage grows without breaking rows without text.
"""
from .params_schema import PARAMS_BY_KEY  # noqa: F401  (re-exported for tests)

HELP_TEXTS = {
    # ---------- model ----------
    "model": "要加载的 GGUF 模型文件。这是唯一必填的参数，服务加载完成后对外提供该模型。",
    "alias": "模型名称别名（逗号分隔），供 API 使用。客户端按名称请求模型时，这些别名同样可以匹配到本模型。",
    "tags": "模型标签（逗号分隔）。仅作展示用途，不参与路由。",
    "hf_repo": "从 Hugging Face 仓库自动下载模型，格式 仓库名:量化。量化可省略（默认 Q4_K_M，大小写不敏感）；若仓库里没有该量化则回退到仓库的第一个文件。",
    "hf_file": "HF 仓库中的具体模型文件。指定后优先于 --hf-repo 中的量化参数。",
    "hf_token": "Hugging Face 访问令牌，用于下载私有仓库或提升下载限额。默认读取 HF_TOKEN 环境变量。",
    "model_url": "模型文件（GGUF）的直接下载 URL，用于无法从 HF/Docker 获取模型的场景。",
    "docker_repo": "从 Docker Hub 自动下载模型。仓库名可省略（默认 ai/），量化可省略（默认 :latest）。格式 ai/<模型>[:量化]。",
    "lora": "LoRA 适配器文件路径，逗号分隔可加载多个。适配器按顺序叠加到基础模型上，微调其输出。",
    "lora_scaled": "LoRA 适配器及自定义缩放系数，格式 路径:缩放（多组逗号分隔）。",
    "lora_init_without_apply": "只加载 LoRA 适配器而不立即应用，之后可通过 POST /lora-adapters 接口动态应用。适合运行时切换适配器。",
    "control_vector": "控制向量（Control Vector）文件，逗号分隔可加载多个。控制向量用于给模型输出注入风格/内容偏向。",
    "control_vector_scaled": "控制向量及自定义缩放系数，格式 路径:缩放（多组逗号分隔）。",
    "control_vector_layer_range": "控制向量作用的层范围（起始-结束），只影响指定范围内的层。",
    "mmproj": "多模态投影器文件（mmproj，GGUF），让模型具备理解图片/音频的能力。必须与主模型配套（如 LLaVA、Qwen-VL 的视觉投影）。",
    "mmproj_url": "多模态投影器文件的 URL，启动时自动下载。",
    "mmproj_auto": "是否自动加载与模型同名配套的 mmproj 文件（使用 HF 下载时尤其有用）。默认开启。",
    "mmproj_offload": "是否将多模态投影器卸载到 GPU。开启可明显加快图片编码速度，代价是占用少量显存。默认开启。",
    "image_min_tokens": "单张图片最少占用的 token 数。仅对动态分辨率的视觉模型有效，默认从模型文件读取。",
    "image_max_tokens": "单张图片最多占用的 token 数。仅对动态分辨率的视觉模型有效，默认从模型文件读取。",
    "mtmd_batch_max_tokens": "批量编码图片时每批允许的最大图片 token 总数，用于限制峰值显存占用。",

    # ---------- context ----------
    "ctx_size": "提示词上下文长度（token 数，n_ctx），决定模型能“记住”多长的历史。0 = 使用模型默认值。调大更耗内存，超出模型训练长度时需配合 RoPE/YaRN 设置扩展。",
    "n_predict": "最多生成的 token 数。-1 = 无限（直到上下文写满或模型自然结束）。服务端每个请求可用 max_tokens 覆盖。",
    "keep": "从提示词开头保留的 token 数（上下文压缩时不丢弃这部分）。-1 = 全部保留。",
    "batch_size": "逻辑最大批大小（n_batch）。影响推理吞吐与内存占用，常用 2048 / 4096。",
    "ubatch_size": "物理最大批大小（ubatch）。单次前向最多处理的 token 数；调低可减小峰值内存，但开销更大。",
    "cache_prompt": "是否启用提示词缓存。相同前缀的请求可复用已有 KV 缓存，避免重复计算，显著加速重复/续聊请求。",
    "cache_reuse": "尝试从缓存复用的最小块大小（token 数）。新请求若能匹配到已缓存的前缀，则直接复用而不重算。需要启用提示词缓存。",
    "cache_ram": "提示词缓存的最大容量（MiB）。-1 = 不限制，0 = 禁用。",
    "cache_idle_slots": "新任务到来时把空闲槽位保存进提示词缓存，使用统一 KV 时再清空。需要 cache-ram。默认开启。",
    "context_shift": "无限生成时上下文写满后，自动丢弃最旧的一段 KV 继续生成（会忘记最早的内容）。",
    "defrag_thold": "（已弃用）KV 缓存碎片整理阈值，现由缓存复用等机制取代，保持默认即可。",
    "ctx_checkpoints": "每个槽位最多创建的上下文检查点数。检查点支持把生成回滚到之前的位置（分支对话）。",
    "checkpoint_min_step": "两个上下文检查点之间的最小间隔（token 数）。0 = 无下限。",
    "kv_offload": "是否将 KV 缓存卸载到 GPU。显存紧张时可关闭，让 KV 留在内存中。",
    "kv_unified": "是否使用跨所有槽位共享的单一统一 KV 缓冲区。槽位数设为自动时默认启用。",
    "cache_type_k": "K 的 KV 缓存数据类型（f16/bf16/f32/q8_0/q4_0 等）。低精度省内存，但可能轻微损失质量。",
    "cache_type_v": "V 的 KV 缓存数据类型（f16/bf16/f32/q8_0/q4_0 等）。低精度省内存，但可能轻微损失质量。",
    "swa_full": "是否使用全尺寸 SWA（滑动窗口注意力）缓存。影响 SWA 模型的显存占用。",
    "rope_scaling": "RoPE 频率缩放方法（如 linear、yarn、longrope 等），默认以模型文件内指定的方法为准。用于把上下文扩展到模型训练长度之外。",
    "rope_scale": "RoPE 上下文缩放因子，把上下文按 N 倍扩展（线性插值）。",
    "rope_freq_base": "RoPE 基础频率，NTK-aware 缩放使用。默认从模型文件读取。",
    "rope_freq_scale": "RoPE 频率缩放因子，把上下文按 1/N 扩展（NTK-aware）。",
    "yarn_orig_ctx": "YaRN：模型原始训练上下文长度。默认取模型文件中的值。",
    "yarn_ext_factor": "YaRN：外推混合因子。0.0 = 纯插值；调大后更多外推，长上下文质量可能更好但对取值敏感。",
    "yarn_attn_factor": "YaRN：sqrt(t) 缩放或注意力幅度因子。",
    "yarn_beta_slow": "YaRN：高修正维度 alpha。",
    "yarn_beta_fast": "YaRN：低修正维度 beta。",

    # ---------- sampling ----------
    "temp": "采样温度，控制随机性：越低越确定、越集中，越高越发散。0 = 贪心解码（总是选概率最高的 token）。常用 0.5–1.0。",
    "top_k": "Top-K 采样：只保留概率最高的 K 个 token 参与采样。0 = 禁用，常用 40。",
    "top_p": "核采样（nucleus）：保留概率累计达到 p 的最小 token 集合。1.0 = 禁用，常用 0.9。",
    "min_p": "Min-P 采样：丢弃概率低于最高 token 概率 p 倍的 token。0 = 禁用。适合长文，能减少无关 token。",
    "typical_p": "局部典型采样参数 p：保留概率最接近典型值的 token。1.0 = 禁用。",
    "top_n_sigma": "Top-N-sigma 采样：保留概率分布在 N 个标准差范围内的 token。-1.0 = 禁用。",
    "xtc_probability": "XTC（极端 token 截断）采样概率：当最高概率超过阈值时，按此概率丢弃低概率 token。0 = 禁用。",
    "xtc_threshold": "XTC 采样阈值：最高 token 概率超过该值时才触发 XTC。1.0 = 禁用。",
    "repeat_penalty": "重复惩罚：对重复出现的 token 序列施加惩罚。>1.0 抑制重复，<1.0 反而鼓励重复，1.0 = 禁用。常用 1.05–1.3。",
    "presence_penalty": "存在惩罚：对已经出现过的 token 施加固定惩罚（不区分出现次数）。正值抑制重复。0 = 禁用。",
    "frequency_penalty": "频率惩罚：按 token 出现次数的比例施加惩罚。0 = 禁用。",
    "dry_multiplier": "DRY（Don't Repeat Yourself）采样乘数。0 = 禁用。用于强力抑制重复短语。",
    "dry_base": "DRY 采样的底数，影响对重复 n-gram 的惩罚强度。",
    "dry_allowed_length": "DRY 采样允许的重复长度（token 数），短于该长度的 n-gram 不受惩罚。",
    "dry_penalty_last_n": "DRY 惩罚考察的最近 token 数量。0 = 禁用。",
    "dry_sequence_breaker": "DRY 采用的序列分隔符（会清除默认分隔符列表）。设为 none 表示不使用任何分隔符。",
    "adaptive_target": "adaptive-p：目标 token 概率（0.0–1.0）。采样器动态调节温度，使 top token 概率接近该目标。负值 = 禁用。",
    "adaptive_decay": "adaptive-p：目标自适应的衰减率。越小越敏感，越大越平稳（0.0–0.99）。",
    "repeat_last_n": "重复惩罚考察的最近 token 数量。0 = 禁用。",
    "seed": "随机数种子。相同种子 + 相同参数 = 相同输出（可复现）。默认随机。",
    "mirostat": "启用 Mirostat 自适应采样，使输出困惑度稳定在目标熵附近。启用后 Top-K / 核采样 / 局部典型采样会被忽略。",
    "mirostat_lr": "Mirostat 学习率 eta：温度调整的步长大小。",
    "mirostat_ent": "Mirostat 目标熵 tau：越大输出越多样。",
    "dynatemp_range": "动态温度范围：温度在最低与最高之间的摆动幅度。0 = 禁用。",
    "dynatemp_exp": "动态温度指数，决定温度随概率变化的曲线形状。",
    "ignore_eos": "忽略结束符（EOS）并继续生成（等效于对 EOS 加 logit-bias 无穷大），通常配合生成长度限制使用。",
    "backend_sampling": "是否把采样放在计算后端（如 GPU）上执行。实验性功能，默认关闭。",
    "samplers": "生成时依次应用的采样器，用分号分隔，如 penalties;dry;top_k;top_p;min_p;temperature。留空 = 使用内置默认顺序。",
    "sampler_seq": "简化版的采样器顺序，是 --samplers 的快捷写法。",
    "logit_bias": "调整指定 token 出现的可能性，格式 TOKEN_ID(+/-)偏置。如 15043+1 提高 token “ Hello” 的概率，15043-1 降低。多组逗号分隔。",
    "grammar": "用类 BNF 文法约束生成内容（可参考 grammars/ 目录的示例），保证输出符合文法结构。",
    "grammar_file": "从文件读取文法，用于约束生成内容。",
    "json_schema": "用 JSON Schema 约束生成，使输出为符合模式的 JSON（如 {} 表示任意 JSON 对象）。带外部 $ref 的模式需先用工具转成文法。",
    "json_schema_file": "从文件读取 JSON Schema，约束生成输出为符合模式的 JSON。",

    # ---------- basic panel extras (跨 tab 的常用参数) ----------
    "n_gpu_layers": "放入显存（VRAM）的最大模型层数（-ngl）。可填具体层数、auto（按显存自动决定）或 all（全部卸载）。GPU 层数越多推理越快，但需要足够显存。",
    "flash_attn": "Flash Attention 开关：on / off / auto。FA 加速注意力计算并降低显存占用（长上下文下收益明显）；auto = 模型与后端支持时启用。",
    "split_mode": "多 GPU 之间的模型切分方式：none = 只用一块 GPU；layer（默认）= 按层与 KV 流水线切分；row = 按行切分权重（并行）；tensor = 权重与 KV 都切分（实验性，并行）。",
    "host": "服务监听地址。127.0.0.1 仅限本机访问，0.0.0.0 允许局域网内其他设备访问。地址以 .sock 结尾时绑定 UNIX socket。",
    "port": "服务监听的 HTTP 端口。",
    "parallel": "服务端槽位数（并发请求数）。-1 = 按内存自动决定。每个槽位有独立的 KV 缓存，槽位越多可同时进行的对话越多。",
    "webui": "是否启用内置 Web UI（启动后访问 http://地址:端口 的内置网页）。",
    "verbose": "是否输出最详细的调试日志（记录所有级别的信息），用于排查问题。",
    "reasoning": "聊天中是否启用思考/推理（on / off / auto）。auto = 由聊天模板自动检测（如 DeepSeek-R1 系列）；off = 不输出思考过程。",
    "spec_type": "投机解码类型（逗号分隔可叠加）：draft-simple / draft-eagle3 / draft-mtp 等草稿模型类，ngram-simple / ngram-map-k / ngram-cache 等 n-gram 匹配类。用小模型或历史 n-gram 预测后续 token，主模型批量验证，可显著加速生成。none = 关闭。",
    "draft_max": "投机解码每步最多起草的 token 数。越多潜在加速越大，但被主模型拒绝的概率也越高。",

    # ---------- gpu ----------
    "device": "用于卸载（offload）的设备列表，逗号分隔（如 CUDA0,CUDA1）；none = 不卸载到 GPU。可用 --list-devices 查看可用设备（主窗口 GPU层数 旁会显示检测结果）。",
    "load_mode": "模型加载模式：auto = mmap（设备不支持时除外）；none = 无特殊模式；mmap = 内存映射加载（加载稍慢但可能减少换页）；mlock = 把模型固定在内存中，防止系统交换/压缩；mmap+mlock = 两者都用；dio = 可用时走 DirectIO。",
    "tensor_split": "模型卸载到各 GPU 的比例，逗号分隔的权重。如 3,1 表示第一块 GPU 承担 3/4、第二块 1/4，适合显存不等的 GPU 组合。",
    "main_gpu": "主 GPU 的索引。split-mode=none 时整个模型放在它上面；split-mode=row 时存放中间结果与 KV。默认 0。",
    "op_offload": "是否把宿主机上的张量运算卸载到设备（GPU）上执行，可减少 CPU-GPU 之间的数据搬运。",
    "cpu_moe": "把所有 MoE（混合专家）层的权重保留在 CPU 内存中（其余层仍可卸载到 GPU），可显著节省显存，MoE 模型常用。",
    "n_cpu_moe": "把前 N 层的 MoE 权重保留在 CPU 内存中。",
    "mmap": "（已弃用，由 --load-mode 取代）是否内存映射模型文件。关闭 mmap 加载更慢，但不使用 mlock 时可能减少换页。",
    "mlock": "（已弃用，由 --load-mode 取代）强制系统把模型固定在物理内存中，而不是交换或压缩。",
    "no_host": "绕过 host buffer，允许使用额外的缓冲区。",
    "repack": "是否启用权重重打包（把权重重排成更适合计算的布局）。",
    "direct_io": "（已弃用，由 --load-mode 取代）可用时使用 DirectIO。",
    "fit": "是否自动调整未设置的参数以适配设备内存（on/off）。显存不足时自动降低各项占显存的参数。",
    "fit_target": "--fit 每块设备保留的目标余量，逗号分隔的数值列表。",
    "fit_ctx": "--fit 允许设置的最小上下文大小。",
    "check_tensors": "检查模型张量数据中是否存在无效值（如 NaN），用于校验文件完整性。",
    "override_tensor": "覆盖张量的缓冲区类型，格式 <张名模式>=<buffer 类型>，多组逗号分隔。",
    "override_kv": "高级选项：按键覆盖模型元数据，格式 KEY=TYPE:VALUE，多组逗号分隔。类型：int、float、bool、str。例：tokenizer.ggml.add_bos_token=bool:false。",
    "warmup": "加载后是否执行一次空跑预热。预热会唤醒缓存与内存分配，使第一次真实请求更快。",
    "rpc": "RPC 服务器列表（host:port，逗号分隔），通过 llama-rpc 把计算卸载到远程机器。",
    "threads": "生成（decode）阶段使用的 CPU 线程数。",
    "threads_batch": "批处理/prompt 处理阶段使用的线程数。默认与 --threads 相同。",
    "cpu_mask": "CPU 亲和掩码（任意长度的十六进制字符串），用于绑定到特定核心。与 cpu-range 互补。",
    "cpu_range": "CPU 亲和范围（lo-hi，如 0-7），用于绑定到特定核心区间。与 --cpu-mask 互补。",
    "cpu_strict": "是否使用严格 CPU 放置（严格按亲和配置把线程绑定到核心）。",
    "cpu_mask_batch": "批处理/prompt 处理阶段的 CPU 亲和掩码（十六进制）。默认与 --cpu-mask 相同。",
    "cpu_range_batch": "批处理/prompt 处理阶段的 CPU 亲和范围。默认与 --cpu-range 相同。",
    "cpu_strict_batch": "批处理/prompt 处理阶段是否使用严格 CPU 放置。默认与 --cpu-strict 相同。",
    "poll": "等待工作时的轮询级别（0 = 不轮询）。部分系统上可降低延迟。",
    "poll_batch": "批处理阶段是否使用轮询等待工作。默认与 --poll 相同。",
    "prio": "进程/线程优先级：low(-1)、normal(0)、medium(1)、high(2)、realtime(3)。",
    "prio_batch": "批处理/prompt 处理阶段使用的进程/线程优先级：low(-1)、normal(0)、medium(1)、high(2)、realtime(3)。与 --prio 相同，但作用于批处理阶段。",
    "numa": "NUMA 优化：distribute = 在所有节点间均匀分布执行；isolate = 只在执行起始节点的 CPU 上创建线程；numactl = 使用 numactl 提供的 CPU 映射。",
    "perf": "是否启用 libllama 内部性能计时，输出各阶段耗时，用于性能分析。",

    # ---------- server ----------
    "reuse_port": "允许多个 socket 绑定到同一端口（多实例/多网卡场景有用）。",
    "api_prefix": "服务提供的 URL 前缀路径，不带末尾斜杠。设置后 API 地址变为 http://host:port/<前缀>/v1/...。",
    "path": "提供静态文件的目录（例如用自定义页面替换内置 WebUI）。",
    "cont_batching": "是否启用连续批处理（dynamic batching）。允许新请求插入正在进行的生成批次，提高多请求下的整体吞吐。",
    "slot_prompt_similarity": "请求的 prompt 与槽位 prompt 需要匹配到什么程度才能复用该槽位（0.0 = 禁用）。前缀匹配时复用槽位及其 KV 缓存，避免重算。",
    "slots": "是否暴露槽位监控端点（GET /slots 查询各槽位状态）。",
    "slot_save_path": "保存槽位 KV 缓存的路径（写盘），用于跨进程复用槽位缓存。",
    "sleep_idle_seconds": "服务器空闲多少秒后进入睡眠（释放 GPU 显存），-1 = 禁用。",
    "timeout": "服务器读/写超时时间（秒）。",
    "sse_ping_interval": "服务器 SSE 心跳 ping 间隔（秒），-1 = 禁用。防止中间代理断开长连接。",
    "threads_http": "处理 HTTP 请求的线程数。",
    "metrics": "启用 Prometheus 兼容的 metrics 端点（GET /metrics），用于监控。",
    "props": "允许通过 POST /props 动态修改全局属性（如温度等采样参数），无需重启。",
    "webui_config": "内置 WebUI 的默认设置 JSON 文本（覆盖内置默认值），直接粘贴 JSON。",
    "webui_config_file": "内置 WebUI 默认设置的 JSON 文件路径（覆盖内置默认值）。",
    "api_key": "用于认证的 API 密钥，多个可逗号分隔。客户端需在 Authorization 头携带 Bearer 密钥才能访问。",
    "api_key_file": "包含 API 密钥的文件路径，每行一个；以 # 开头的行视为注释。",
    "ssl_key_file": "PEM 编码的 SSL 私钥文件路径，用于启用 HTTPS。",
    "ssl_cert_file": "PEM 编码的 SSL 证书文件路径，用于启用 HTTPS。",
    "cors_origins": "CORS 允许的源（origin）列表，逗号分隔。* = 允许所有来源（跨域访问控制）。",
    "cors_methods": "CORS 允许的 HTTP 方法列表，逗号分隔。",
    "cors_headers": "CORS 允许的请求头列表，逗号分隔。",
    "cors_credentials": "CORS 是否允许携带凭证（cookie 等）。",
    "embedding": "限制为仅支持 embedding（向量化）用途。只与专用 embedding 模型配合使用。",
    "rerank": "在服务器上启用 rerank（相关性重排）端点。",
    "pooling": "embedding 的池化方式。不指定时使用模型默认（如 mean、cls）。",
    "embd_normalize": "embedding 归一化方式：-1=不归一化，0=按最大绝对值缩放到 int16，1=出租车距离（L1），2=欧几里得（L2），>2=p 范数。",
    "media_path": "加载本地媒体文件的目录；消息中可用相对路径的 file:// URL 引用这些文件（让模型读取本地图片等）。",
    "models_dir": "路由器（多模型路由）服务使用的模型文件目录。",
    "models_preset": "路由器服务的模型预设 INI 文件路径。",
    "models_max": "路由器服务同时加载的最大模型数，0 = 不限制。",
    "models_autoload": "路由器服务是否自动加载模型（按需加载请求到的模型）。",

    # ---------- spec ----------
    "draft_model": "投机解码用的草稿模型（GGUF），供 draft-* 类投机使用。必须与主模型配套（同架构、分词器）；EAGLE-3/DFlash/DSpark 草稿模型需用 --target-model-dir 转换。",
    "spec_draft_hf": "同 --hf-repo，但用于自动下载草稿模型。格式 <user>/<model>[:量化]。",
    "n_gpu_layers_draft": "草稿模型放入显存（VRAM）的最大层数。可填数字、auto 或 all。",
    "device_draft": "草稿模型卸载使用的设备列表（逗号分隔）。none = 不卸载，默认跟随 --device。",
    "cpu_moe_draft": "把草稿模型的所有 MoE 层权重保留在 CPU 内存中。",
    "n_cpu_moe_draft": "把草稿模型前 N 层的 MoE 权重保留在 CPU 内存中。",
    "cache_type_k_draft": "草稿模型 KV 缓存 K 的数据类型（f16/q8_0 等）。",
    "cache_type_v_draft": "草稿模型 KV 缓存 V 的数据类型（f16/q8_0 等）。",
    "override_tensor_draft": "覆盖草稿模型张量的缓冲区类型，格式 <张名模式>=<buffer 类型>，多组逗号分隔。",
    "threads_draft": "草稿模型生成使用的线程数。默认与 --threads 相同。",
    "threads_batch_draft": "草稿模型批处理/prompt 处理使用的线程数。默认与 --threads-draft 相同。",
    "spec_draft_cpu_mask": "草稿模型的 CPU 亲和掩码（十六进制）。与 cpu-range-draft 互补，默认与 --cpu-mask 相同。",
    "spec_draft_cpu_range": "草稿模型的 CPU 亲和范围。与 --cpu-mask-draft 互补。",
    "spec_draft_cpu_strict": "草稿模型是否使用严格 CPU 放置。默认与 --cpu-strict 相同。",
    "spec_draft_prio": "草稿模型进程/线程优先级：0-normal、1-medium、2-high、3-realtime。",
    "spec_draft_poll": "草稿模型是否使用轮询等待工作。默认与 --poll 相同。",
    "spec_draft_cpu_mask_batch": "草稿模型批处理/prompt 处理的 CPU 亲和掩码。默认与 --cpu-mask 相同。",
    "spec_draft_cpu_strict_batch": "草稿模型批处理/prompt 处理是否使用严格 CPU 放置。默认与 --cpu-strict-draft 相同。",
    "spec_draft_prio_batch": "草稿模型批处理/prompt 处理的进程/线程优先级：0-normal、1-medium、2-high、3-realtime。",
    "spec_draft_poll_batch": "草稿模型批处理是否使用轮询等待工作。默认与 --poll-draft 相同。",
    "draft_min": "投机解码每步最少起草的 token 数，低于该值时不起草。",
    "draft_p_min": "投机解码的最小起草概率（贪心）。概率低于该值的候选 token 不会被起草。",
    "spec_draft_p_split": "投机解码分支拆分概率：并行起草多个候选分支时，次优候选概率超过该阈值才拆出分支（默认 0.10）。",
    "spec_draft_backend_sampling": "是否把草稿模型的采样放在后端（GPU）上执行。草稿模型默认已用后端采样，此选项可关闭。",
    "spec_ngram_size_n": "ngram-simple：查找用的 n-gram 长度 N（向前回看多少个 token 匹配模式）。",
    "spec_ngram_size_m": "ngram-simple：起草的 m-gram 长度 M（匹配后起草多少 token）。越大潜在加速越高，但接受率可能降低。",
    "spec_ngram_min_hits": "ngram-simple：n-gram 在历史中出现的最少次数，达到才可用作草稿候选。",
    "spec_ngram_mod_n_min": "ngram-mod：查找使用的最少 ngram token 数。ngram-mod 用 LCG 滚动哈希把 n-gram 映射到下一 token，哈希池跨所有槽位共享。",
    "spec_ngram_mod_n_max": "ngram-mod：查找使用的最多 ngram token 数。",
    "spec_ngram_mod_n_match": "ngram-mod：ngram 查找长度（匹配窗长）。ngram-mod 内存恒定（约 16MB），可产生变长草稿，适合代码迭代、推理模型复述思考、摘要等场景。",
    "spec_ngram_map_k_size_n": "ngram-map-k：查找的 n-gram（key）长度 N。在 token 历史中查找当前 key。",
    "spec_ngram_map_k_size_m": "ngram-map-k：起草的 m-gram 长度 M（key 后面跟随的 token 数）。",
    "spec_ngram_map_k_min_hits": "ngram-map-k：key 必须在历史中出现的最少次数（默认 1）。同一 m-gram 多次跟随 key 时直接用作草稿，适合重复性文本（如改写源码）。",
    "spec_ngram_map_k4v_size_n": "ngram-map-k4v（实验性）：查找的 n-gram（key）长度 N。每个 key 跟踪最多 4 个候选 m-gram，用统计选出明显更频繁的一个作草稿。",
    "spec_ngram_map_k4v_size_m": "ngram-map-k4v：起草的 m-gram 长度 M。",
    "spec_ngram_map_k4v_min_hits": "ngram-map-k4v：key 必须在历史中出现的最少次数（默认 1）。适合大量较长重复的场景。",
    "lookup_cache_static": "lookup 解码用的静态查找缓存文件路径（预先构建，生成过程中不更新）。",
    "lookup_cache_dynamic": "lookup 解码用的动态查找缓存文件路径（生成过程中持续更新累积）。",

    # ---------- chat ----------
    "jinja": "是否使用 Jinja 模板引擎处理聊天（推荐）。绝大多数现代模型的对话格式依赖模型文件内嵌的 Jinja 模板，禁用会回退到内置模板。",
    "chat_template": "自定义 Jinja 聊天模板（直接粘贴模板文本）。不指定时使用模型元数据中的模板。",
    "chat_template_file": "自定义 Jinja 聊天模板的文件路径。不指定时使用模型元数据中的模板。",
    "chat_template_kwargs": "传给 JSON 模板解析器的附加参数，必须是合法 JSON 对象字符串，如 {\"key1\":\"value1\"}。",
    "skip_chat_parsing": "强制使用纯内容解析器（即使指定了 Jinja 模板也不应用），模型输出所有内容不做模板解析。",
    "prefill_assistant": "最后一条消息是 assistant 消息时，是否预填充其内容（从已有回复继续写）。默认启用。",
    "reasoning_format": "控制思考标签（think 标签）的解析与返回方式：none = 不解析，思考留在 message.content 中；deepseek = 思考内容放入 message.reasoning_content；deepseek-legacy = content 中保留 think 标签，同时填充 reasoning_content。默认 auto。",
    "reasoning_budget": "思考的 token 预算：-1 = 不限制，0 = 立即结束（不思考），N>0 = 最多思考 N 个 token。",
    "reasoning_budget_message": "思考预算耗尽时，在思考结束标签前注入的消息（提示模型立即总结收尾）。",
    "reasoning_preserve": "在完整历史中保留推理轨迹（不只是最后一条 assistant 消息）。兼容具有 supports_preserve_reasoning 能力的模板（如 Z.ai 的保留思考模式）。",

    # ---------- agent ----------
    "agent": "是否启用 CORS 代理和全部内置工具（AI agent 能力）。出于安全考虑，默认会把 --cors-origins 限制为 localhost。不可信环境请勿启用。",
    "tools": "为 AI agent 启用内置工具（实验性）：read_file、file_glob_search、grep_search、exec_shell_command、write_file、edit_file、get_info。填 all 启用全部。出于安全考虑，默认会把 --cors-origins 限制为 localhost。不可信环境请勿启用。",
    "tools_runtime": "在隔离的运行时环境中执行工具（实验性）：docker:<镜像>/podman:<镜像> = 新建容器并复用、服务退出时清理；docker-container:<id>/podman-container:<id> = 复用已有容器（退出不停止）；ssh:<目标> = 通过 SSH 在远程 POSIX 主机执行（需密钥认证+受信主机密钥）。默认使用宿主环境。",
    "mcp_servers_config": "MCP 服务器定义 JSON 文件的路径（Cursor 兼容格式）。不可信环境请勿启用；出于安全考虑，默认会把 --cors-origins 限制为 localhost。",
    "mcp_servers_json": "MCP 服务器定义的 JSON 文本（Cursor 兼容格式，直接粘贴）。不可信环境请勿启用；出于安全考虑，默认会把 --cors-origins 限制为 localhost。",
    "webui_mcp_proxy": "是否启用 MCP CORS 代理（实验性）。不可信环境请勿启用。",

    # ---------- advanced ----------
    "special": "是否输出特殊 token（如 bos/eos）。默认关闭。",
    "reverse_prompt": "出现指定 prompt 时停止生成并返回控制（交互模式使用）；多组可逗号分隔。",
    "spm_infill": "代码补全（infill）使用 Suffix/Prefix/Middle 模式（部分模型偏好此顺序）。默认使用 Prefix/Suffix/Middle。",
    "escape": "是否处理转义序列（\\n、\\r、\\t、\\'、\\\"、\\\\）。",
    "offline": "离线模式：强制使用缓存，阻止一切网络访问（如模型下载）。",
    "log_verbosity": "日志详细度阈值，超过阈值的消息被忽略。0=一般输出，1=错误，2=警告，3=信息，4=trace，5=debug（数值越大越详细）。默认为 4 (trace)：llama.cpp 自 2026 年 5 月起（#23021）在 3 (info) 级别下会抑制模型加载、显存、上下文等详细信息，运行信息面板需要 4 及以上才能完整显示；设为 3 或更低可让日志更简洁。",
    "log_colors": "日志是否使用颜色（on/off/auto）。auto = 输出到终端时启用颜色。",
    "log_file": "把服务器日志写入指定文件。",
    "log_disable": "禁用日志输出。",
    "log_prompts_dir": "把提示词保存到指定目录（目录不存在会自动创建；仅供调试）。",
    "log_prefix": "日志消息带前缀。",
    "log_timestamps": "日志消息带时间戳。",
    "extra_args": "额外参数，原样附加到 llama-server 命令末尾，每行一个。用于界面未暴露的参数（如 --flash-attn 的某个新别名）。",
}


def has_help(key: str) -> bool:
    """Whether an explanation exists for this param key."""
    return key in HELP_TEXTS


def help_text(key: str) -> str:
    """Chinese-source explanation literal (UI applies t()); '' when absent."""
    return HELP_TEXTS.get(key, "")


def help_i18n_strings():
    """Every explanation string (i18n coverage test feed)."""
    return list(HELP_TEXTS.values())
